// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhhcuaxjmonfkimvgghw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaGN1YXhqbW9uZmtpbXZnZ2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzMyNzMsImV4cCI6MjA2ODQ0OTI3M30.vAjZKpB-HspPBsMQkA8b2hSanynswMIIrqSJHo2NkR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});